data_path: '/users/bdillon/projects/rl/data/gg_ttbar_budbud_unweighted_events_rlready.pkl'
masses_path: '/users/bdillon/projects/rl/data/gg_ttbar_budbud_unweighted_events_mass_corrs.npy'
mass_corrs: False
reuse_actions: False
graph_masses: False
matrix2py_path: '/users/bdillon/MG5_aMC_v3_6_2/ttbar_gg_budbud/SubProcesses/P1_gg_ttx_budxbxuxd/'
paramcard_path: '/users/bdillon/MG5_aMC_v3_6_2/ttbar_gg_budbud/Cards/param_card.dat'
process: 'tt'
num_steps: 5
sparse_rewards: False
num_episodes: 6000000
d_input: 4
d_model: 128
num_heads: 4
num_layers: 4
position_embedding: False
dropout: 0.1
eval_every: 100000
test_frac: 0.05
num_eval: 10000
gamma: 0.1
learning_rate: 0.00005
batch_size: 128
scale_reward: 0.1
memory_size: 200000
target_update_freq: 1000
epsilon_start: 1.0
epsilon_end: 0.5
epsilon_decay: 0.999
