data_path: '/users/bdillon/projects/rl/data/tttt_budbudbudbud_unweighted_events_rlready.pkl'
reuse_actions: False
matrix2py_path: '/users/bdillon/MG5_aMC_v3_6_2/tttt_budbudbudbud_me/SubProcesses/P1_gg_ttxttx_t_bwp_wp_udx_tx_bxwm_wm_uxd_t_bwp_wp_udx_tx_bxwm_wm__1/'
paramcard_path: '/users/bdillon/MG5_aMC_v3_6_2/tttt_budbudbudbud_me/Cards/param_card.dat'
process: 'tttt'
num_steps: 11
sparse_rewards: False
num_episodes: 6000000
d_input: 4
d_model: 128
num_heads: 4
num_layers: 4
position_embedding: False
dropout: 0.1
eval_every: 100000
test_frac: 0.05
num_eval: 10000
gamma: 0.5
learning_rate: 0.00005
batch_size: 128
scale_reward: 0.1
memory_size: 200000
target_update_freq: 1000
epsilon_start: 1.0
epsilon_end: 0.5
epsilon_decay: 0.999
init_net: '/users/bdillon/projects/rl/results/tttt_run8/policy_net_2399999.pth'
